name: Hello World

on:
    push:
        branches:
            - main

jobs:
    hello_world_jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello World!"

            - name: Print Date
              run: date

            - name: List Directory Contents
              run : ls -l
